### ISSUE TITLE
库在maven上找不到？yalong.site这两个库是在哪里下载的呢？

### ISSUE THREAD

**Issue by za123** [4379711/lol-helper#1]
<dependency>
            <groupId>yalong.site</groupId>
            <artifactId>swing-ui</artifactId>
            <version>1.0</version>
        </dependency>

        <dependency>
            <groupId>yalong.site</groupId>
            <artifactId>dm</artifactId>
            <version>1.0</version>
        </dependency>

**Comment by 4379711** [comment]
兄弟,你这么快的吗,我昨天才上传到github的,你就看到了...
这俩库是我安装到本地仓库的,现在代码才写了一半,等全写完了一起发布

**Comment by za123** [comment]
好的，可以提交了一起改哈

**Comment by za123** [comment]
好的
