### ISSUE TITLE
可以添加一个像Wegame那样的自定义一键喊话的功能吗

### ISSUE THREAD

**Issue by Milo-Zhao** [4379711/lol-helper#12]
我玩的台服，wegame的功能用不了，经常因为没时间打字沟通不到位，能不能做个类似的功能？

**Comment by 4379711** [comment]
很容易,你把喊话代码copy一下,然后自己预先写好喊话内容,绑定固定快捷键即可

**Comment by Milo-Zhao** [comment]
哈哈哈，对，我这样做了一个，你可以看看我的fork
