### ISSUE TITLE
发送战绩失败

### ISSUE THREAD

**Issue by 4379711** [4379711/lol-helper#16]
问题描述:按快捷键发送战绩,战绩在聊天框一闪而过,但是没有发送出去,聊天框内没有出现要发送的内容,这种情况有时候出现,有时候不出现

解决方案: **基本无解**,这是因为被游戏**屏蔽**了,游戏内会屏蔽很多词汇,包括数字也屏蔽,比如你手动输入123456789,你会发现也发不出去

**Comment by acsxzz** [comment]
还没发几条就被禁言24小时了...

**Comment by 4379711** [comment]
没办法 ,游戏内检测敏感词,只能自己改改了
