### ISSUE TITLE
打开提示请先启动游戏

### ISSUE THREAD

**Issue by supershuke** [4379711/lol-helper#19]
如题

**Comment by 4379711** [comment]
这不是提醒你,让你先启动游戏嘛.....

**Comment by supershuke** [comment]
我已经启动游戏了，但是他还是提示请先启动游戏

**Comment by supershuke** [comment]
![{CE0D5292-838A-4ccf-B1A5-0C1744FC79A3}](https://github.com/4379711/lol-helper/assets/160384097/5d32bf5a-3411-44d2-982a-9e4bdca80fab)
如图

**Comment by chansee97** [comment]
永远都有人不看readme，管理员权限启动

**Comment by supershuke** [comment]
谢谢，看了redme文件的教程已经解决了
