### ISSUE TITLE
一点关于战绩发送的建议

### ISSUE THREAD

**Issue by Cz1544252489** [4379711/lol-helper#20]
如果出现无法发战绩是因为玩家的名字或者数字的影响，在标记是哪个玩家的时候可以考虑使用英雄名字代替，最好也可以设置一个框让使用者选择要使用玩家ID还是当前使用的英雄的名字。

**Comment by 4379711** [comment]
一般来说,进游戏了再切换到软件去配置感觉不太好,手速慢的可能队友已经一级团结束了,现在也在纠结怎么弄,90%的情况是因为数字发不出去,比如1234就发不出去,这种情况下只能另想办法了

**Comment by 4379711** [comment]
而且我试了用大写或者①②③④,也发不出去,所以暂时没有解决方案

**Comment by Cz1544252489** [comment]
那完全可以忽视数字，纯数字ID占比很低，只要有任何其他内容就可以作为标识，不过这应该难度上又高了吧。

**Comment by yuanshangyujingshierlou** [comment]
可以尝试下分段发送呢

**Comment by Cz1544252489** [comment]
哈哈哈，对了现在几乎都变成带数字编号的了。
