### ISSUE TITLE
卡炫彩只能在训练营了其他模式失效

### ISSUE THREAD

**Issue by kanach4n** [4379711/lol-helper#21]
还能救回来吗这个功能

**Comment by chansee97** [comment]
马服应该是给接口做验证了

**Comment by WJZ-P** [comment]
是的，也发现了，不知道怎么办呢

**Comment by 4379711** [comment]
被TX针对性校验了,估计以后也难以放开限制

**Comment by WJZ-P** [comment]
感觉可能跟这个月月初B站的一个视频有关系，我也是看了那个说卡炫彩的视频才来了解




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月27日(星期一) 上午9:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [4379711/lol-helper] 卡炫彩只能在训练营了其他模式失效 (Issue #21)














 
被TX针对性校验了,估计以后也难以放开限制

**Comment by afei0711zz** [comment]
所有现在没有卡炫彩了吗

**Comment by 4379711** [comment]
> 所有现在没有卡炫彩了吗

没有了
