### ISSUE TITLE
获取进程的命令报语法错误

### ISSUE THREAD

**Issue by Nottoocold** [4379711/lol-helper#22]
本人电脑环境：
Windows 11 专业版
版本	23H2
安装日期	‎2024/‎5/‎15
操作系统版本	22631.3593

命令都是以管理员身份运行

1.先按 WMIC PROCESS WHERE name=\"LeagueClientUx.exe\" GET commandline 执行，报错如下
节点 - DESKTOP-6F9E09C
错误:
描述 = 无效查询

2.再按 WMIC PROCESS WHERE "name='LeagueClientUx.exe'" GET commandline ，成功获取到port和token

**Comment by 4379711** [comment]
你的意思是要给进程名加上引号,就能适配win11吗

**Comment by Nottoocold** [comment]
> 你的意思是要给进程名加上引号,就能适配win11吗

可能是吧

**Comment by 4379711** [comment]
感谢反馈,已添加
