### ISSUE TITLE
安全方案Anti-Cheat Expert中的SGuard组件无法正确运行导致程序失败

### ISSUE THREAD

**Issue by bob-yy** [4379711/lol-helper#25]
描述：在大乱斗中每隔几分钟会报错误，我点击错误信息的详情，跳转到了https://gamesafe.qq.com/article/928.shtml界面。

截图：下面这张图不是我本机的报错信息，但也差不多。应该是安全方案Anti-Cheat Expert中的SGuard组件无法正确运行导致。

![ace安全组件运行失败](https://github.com/user-attachments/assets/d16b5987-65f6-40e5-b0a4-fa8355ca3beb)

结果：
报错会导致程序运行失败，但可以重新连接，然后又会出现同样的错误，一直循环。如果关闭lol-helper，就不再出现异常。

**Comment by bob-yy** [comment]
除了运行游戏时，会导致该失败，在我的机器上其他功能看起来是正常的。

**Comment by bob-yy** [comment]
感觉可能是一键连招导致的，我将一键连招取消，就没有碰到这个错误了。

**Comment by 4379711** [comment]
观察了一段时间,其他人都没发现这个问题,暂时也没好的解决方案
