### ISSUE TITLE
请问下哪个版本支持外服有秒选和接受对局功能

### ISSUE THREAD

**Issue by yjt123789** [4379711/lol-helper#29]
请问下哪个版本支持外服有秒选和接受对局功能

**Comment by 4379711** [comment]
外服我没测试,你随便找一个版本试试,理论上都可以用

**Comment by WuYi5451** [comment]
现在开发人员比较少 对于外服的支持力度有限 等日常bug修完了 有空时有意向调试 不然可以先试试其他优秀工具 比如萨勒芬妮啥的
