### ISSUE TITLE
8.0之后的 jar 复制进 app 文件夹后无法运行

### ISSUE THREAD

**Issue by GitHubd3b7c** [4379711/lol-helper#30]
从8.1.1试到了8.0.2，已经授予了管理员权限但是都无法运行。表现是双击确认授予管理员权限后没反应

**Comment by 4379711** [comment]
以前版本可以吗?

**Comment by 4379711** [comment]
加一下qq群,群里有绿色免安装版本

**Comment by GitHubd3b7c** [comment]
> 以前版本可以吗?

8.0以及之前的版本都可以

**Comment by 4379711** [comment]
现在不确定是哪个问题,github上是自动打包的,一直没变过,先下载绿色版试试吧
