### ISSUE TITLE
你好，我也是一名使用lcu api开发的爱好者，询问一下如何游戏内发送消息，非常感谢。。

### ISSUE THREAD

**Issue by BruceQiu1996** [4379711/lol-helper#5]
你可以看我的仓库，我也有一个lcu的原创插件。如果看到，希望能回复，非常感谢。。

**Comment by 4379711** [comment]
兄弟,不能通过LCU发送消息到对局游戏内,给你提供两个思路:
1.模拟按键,然后发送(本项目的方式)
2.HOOK,直接内存CALL

**Comment by BruceQiu1996** [comment]
Okkk，目前就是用的模拟按键
